version: "3.9"

services:

 # echo-starter
  echo-starter:
    image: "${ECHO_STARTER_IMAGE_NAME}:${ECHO_STARTER_VERSION}"
    container_name: "${ECHO_STARTER_NAME}"
    networks:
      - echostarter
    ports:
      - ${ECHO_STARTER_PORT}:8081
    logging:
      driver: "json-file"
      options:
        max-size: "${CONTAINER_LOG_SIZE}"
        max-file: "${CONTAINER_LOG_COUNT}"
    environment:
      APPLICATION_ENVIRONMENT: "${APPLICATION_ENVIRONMENT}"
      PORT: "8081"
      LOG_LEVEL: "${ECHO_STARTER_LOG_LEVEL}"
      PRETTY_LOG: "${ECHO_STARTER_PRETTY_LOG}"
      OIDC__DOMAIN: "${AUTH0_DOMAIN}"
      OIDC__CLIENT_ID: "${AUTH0_CLIENT_ID}"
      OIDC__CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
      OIDC__CALLBACK_URL: "http://localhost:${ECHO_STARTER_PORT}/oidc"
      SESSION_KEY: "c74fgCV8ub7q9c1FV214t67CzH1dPfIj"
      SESSION_ENCRYPTION_KEY: "0ZAeBrf1MELbyqW2vOqBKao1kwWvBJxu"

      
    entrypoint: ["/app/server"]


networks:
  echostarter:
  
 