name: Go

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/dependabot.yml'
      - '.env'
      - 'docker-compose.yml'
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ main ]
env:
  BINARY: 'server'
  GO_VERSION: '1.18'
  BUILD_PATH: './cmd/server'
  DOCKER_IMAGE_NAME: 'echo-starter'
  
jobs:
  pre_flight:
    runs-on: ubuntu-latest
    
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog : ${{ steps.tag_version.outputs.changelog }}
    steps:
    - name: Establish tags and versions
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [pre_flight]
    steps:
    - name: Echo Tags
      run: |
       echo new_tag: ${{needs.pre_flight.outputs.new_tag}} 
       echo changelog: ${{needs.pre_flight.outputs.changelog}}
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "^${{ env.GO_VERSION }}"

    - name: go mod vendor
      run: |
        go mod tidy -compat="${{ env.GO_VERSION }}" 
        go mod download
        go mod vendor

    - name: move vendor sub folders
      run: |
        mv ./vendor/github.com/fluffy-bunny/sarulabsdi/genny/ ./genny/sarulabsdi/
        rm -rf ./vendor/

    - name: Install Mockgen
      run: |
        go install github.com/golang/mock/mockgen@latest
    - name: Install genny
      run: |
        go version
        go install github.com/cheekybits/genny@latest
    
    - name: GO GENERATE
      run: |
        go generate -x ./...
        rm -rf ./genny/sarulabsdi/
        go mod tidy -compat="${{ env.GO_VERSION }}" 

    # NOTE: This will NOT trigger another run of CI.yml
    - name: AutoCommit
      uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: Apply genny and mockgen changes
       
    - name: Build
      run: |
        go build -mod=mod -v -a -tags netgo -ldflags "-X 'main.version=${{needs.pre_flight.outputs.new_tag}}' -extldflags '-static'" ${{ env.BUILD_PATH }}
    
    - name: Make Upload folder
      run: |
        mkdir -p ./artifacts
        cp ./${{ env.BINARY }} ./artifacts/
        cp ./cmd/server/templates/ ./artifacts/templates/
        cp ./cmd/server/assets/ ./artifacts/assets/
        cp ./cmd/server/css/ ./artifacts/css/
        cp ./cmd/server/js/ ./artifacts/js/
        cd ./artifacts/
        ls -R

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          ./${{ env.BINARY }} 
          ./cmd/server/templates/
          ./cmd/server/assets/
          ./cmd/server/css/
          ./cmd/server/js/
          ./artifacts/


    - name: Test
      run: go test -v ./...

  # Create and post docker image
  build-docker-push-image:
    runs-on: ubuntu-latest
    needs: [ pre_flight, build ]

    steps:
      - name: Echo Tags
        run: |
         echo new_tag: ${{needs.pre_flight.outputs.new_tag}} 
         echo changelog: ${{needs.pre_flight.outputs.changelog}}

      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: inspect build folder
        run: |
          cd ./build
          ls -R

      # If we ever have more than 1 file, tar before actions/upload-artifact
      - name: Fix Execute Bit
        run: |
          chmod +x cmd/server/${{ env.BINARY }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Inspect builder
        run: |
            echo "Name:      ${{ steps.buildx.outputs.name }}"
            echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
            echo "Status:    ${{ steps.buildx.outputs.status }}"
            echo "Flags:     ${{ steps.buildx.outputs.flags }}"
            echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push docker_build - main
        id: docker_build_main
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ./build
          file: ./cmd/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.DOCKER_IMAGE_NAME}}:${{needs.pre_flight.outputs.new_tag}},${{ secrets.DOCKER_HUB_USERNAME }}/${{env.DOCKER_IMAGE_NAME}}:latest
          
      - name: Build and push docker_build - branch
        id: docker_build_branch
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ./cmd/server
          file: ./cmd/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.DOCKER_IMAGE_NAME}}:${{needs.pre_flight.outputs.new_tag}}


      - name: Image digest docker_build
        run: echo ${{ steps.docker_build.outputs.digest }}
 
